pin_crowd_api:
    resource: "@PinCrowdApiBundle/Controller/"
    type:     annotation
    prefix:   /

pin_crowd_kiosk:
    resource: "@PinCrowdKioskBundle/Controller/"
    type:     annotation
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
