<?php

namespace PinCrowd\Api\ScoringBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ScoringController__JMSInjector
{
    public static function inject($container) {
        $instance = new \PinCrowd\Api\ScoringBundle\Controller\ScoringController();
        return $instance;
    }
}
